"""empty message

Revision ID: ceb75ac779c8
Revises: f5b9358984a4
Create Date: 2018-03-05 13:38:48.540337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceb75ac779c8'
down_revision = 'f5b9358984a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mobile', table_name='user')
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('mobile', 'user', ['mobile'], unique=True)
    # ### end Alembic commands ###
