"""empty message

Revision ID: f5b9358984a4
Revises: 1d46d7a2cc4b
Create Date: 2018-03-05 13:37:52.532362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b9358984a4'
down_revision = '1d46d7a2cc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=220), nullable=False))
    op.create_unique_constraint(None, 'user', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
